### PR TITLE
Fill out memoryapi

### PR DESCRIPTION
**Pull request by docbrown**

### CODE REVIEW

**Comment by docbrown** [comment]
Needs #466 first.

**Comment by docbrown** [comment]
Test are failing with:

> Doc-tests winapi
error: An unknown error occurred

They pass on my machine, though. Hmmm...

**Comment by retep998** [comment]
You have functions in `memoryapi` which come from a different library than `kernel32`. Specifically `MapViewOfFileNuma2` which comes from one of `onecore`/`onecoreuap`/`mincore`/`mmos`. In Rust 1.6 inline functions, such as `MapViewOfFile2`, are not lazily instantiated and `ld` fails to strip unreferenced functions so it fails to link. I'm not entirely sure why the doc test fails on current Rust but my guess is that it depends on a symbol which only exists on a newer version of Windows than Appveyor has.

**Comment by retep998** [comment]
Doc tests failing because of https://github.com/rust-lang/rust/issues/44487

**Comment by Susurrus** [comment]
@retep998 This good to merge now?

**Pull request merged**
