### PR TITLE
Add the rest of IMM APIs

### PR DESCRIPTION
**Pull request by ghost**
I add the rest of [IMM APIs](https://docs.microsoft.com/en-us/windows/desktop/api/imm/).

### CODE REVIEW

**Comment by huangjj27** [comment]
Can this PR rebase to the newest master？

**Comment by retep998** [comment]
What happened with the commit history here?!

**Comment by ghost** [comment]
Sorry, I make the mistake.

**Comment by ghost** [comment]
reset done. I'm sorry again.

**Pull request closed without merging**
