### PR TITLE
Add um::winuser::GetTitleBarInfo and missing constants for um::winuser::GetAncestor

### PR DESCRIPTION
**Pull request by nasso**
I also added the relevant `struct`s and `const`s and moved `um::winuser::GetWindowInfo` to the right place to match with the actual order in `WinUser.h`.

### CODE REVIEW

**Comment by MSxDOS** [comment]
Seems like a duplicate of https://github.com/retep998/winapi-rs/pull/751 which is there since March.
@retep998

**Comment by nasso** [comment]
@MSxDOS Yup, a bunch of code is duplicate.
Though other PRs (#749) also containing duplicate code already got merged.
Looks like we would have to cherry-pick the commits to avoid conflicts.

**Comment by retep998** [comment]
This PR has conflicts that need to be resolved.

**Review by retep998 — APPROVED** [review]
This PR is now nothing more than renaming a single parameter to a function, so it is very easy to review.

**Pull request merged**
