### PR TITLE
Add D3D11CalcSubresource function.

### PR DESCRIPTION
**Pull request by jeandudey**
Solves #265.

### CODE REVIEW

**Comment by retep998** [comment]
I'd rather the function be defined in https://github.com/retep998/winapi-rs/blob/master/src/d3d11.rs as the -sys crates are for functions that are linked only.

**Comment by jeandudey** [comment]
Ok, I will move it

**Comment by retep998** [comment]
Also your system clock seems to be configured incorrectly as the timestamp on your commit is significantly in the future.

**Comment by jeandudey** [comment]
Done.

**Comment by retep998** [comment]
Now your system clock is exactly 12 hours behind.

**Comment by jeandudey** [comment]
Now is fixed :+1:

**Comment by jeandudey** [comment]
Yep :'(

**Comment by retep998** [comment]
This PR is out of date and needs a rebase.

**Comment by retep998** [comment]
This commit is already in master but github didn't notice, so closing.

**Pull request closed without merging**
