### PR TITLE
Finish migrating all 0.2 code in /lib to 0.3

### PR DESCRIPTION
**Pull request by Susurrus**
I'm submitting this as 1 big PR because it should a) be relatively easy to review since it's just migrating functions and there's no complicated data structures here and b) there are a ton of merge conflicts as soon as you start modifying `kernel32/mod.rs`, so this will be faster doing this in a big batch rather than having to ask people to update their PRs after every other one is merged.

After this there are only 348 lines of code left to migrate, most of which is covered by #447, #500, and #501.

The following should be noted:

- This PR contains only the migration pieces from #426 whose author said it might be a while before he can work on that PR again
- It also contains the same changes as done in #507, which was submitted after I made this change.

### CODE REVIEW

**Comment by Susurrus** [comment]
@retep998 I was going to go ahead and basically finish kernel32 as part of this PR, or would you rather I not make this any bigger than it already is?

**Comment by Susurrus** [comment]
Okay, the scope of this expanded a bit and this PR entails the porting of ALL functionality currently left in `/lib`. This means it supplants all the work done across various PRs that are wrapping up the 0.2 -> 0.3 conversion: #426, 447, #500, #501, and #507. It's likely most of those PRs will still have code changes that should be merged even after rebasing upon this work.

@retep998 At this people `RtlCopyMemory` is the only function left to be ported from the old kernel32 header, but I'm unsure how to proceed. It's a macro that either acts as a straight `memcpy` or uses a `memcpy_inline` function which wraps `memcpy` in a overlapping range check. I'm unsure how you want to handle this. If you'd rather just merge this and address that in your own commit, that might be easiest. Let me know what you want to do.

**Comment by retep998** [comment]
You might want to possibly consider fixing the merge conflicts maybe.

**Comment by Susurrus** [comment]
@retep998 You're planning to merge this before #447? I've been letting this sit as I figured you'd do that one first.

**Comment by Susurrus** [comment]
@retep998 Ping!

**Pull request merged**
