### PR TITLE
Add basic support for dwmapi and ANIMATIONINFO

### PR DESCRIPTION
**Pull request by application-developer-DA**
This pull request consists of several commits:
- Adds support of `DmwGetWindowAttribute()` function used for getting some useful windows attributes (and it also adds required constants that are usually passed to this function).
- Adds `ANIMATIONINFO` structure to the `winuser` module along with some constants that are usually used in conjunction with `ANIMATIONINFO` structure and `SystemParametersInfo()` function.

P.S.: The previous pull requested was not accepted for a long time, due to that it was not in a 'mergeable' state today as some other commits were pushed to the master branch meanwhile. I pulled the changes (with `--rebase` enabled), so now it should work.

### CODE REVIEW

**Comment by retep998** [comment]
This PR will need to be updated for the winapi 0.3 new world order. https://github.com/retep998/winapi-rs/issues/316

**Comment by application-developer-DA** [comment]
Hi @retep998 , I updated the pull request, please have a look. Not it should work (passes CI tests/builds).

I also have one question. Did I get it right that the current master branch is not in a usable state? I tried to use the new master branch for my project and now it does not work as everything inside `lib/*` is not accessible anymore, so I'm not able to call `gdi32` functions for instance.

**Comment by retep998** [comment]
@application-developer-DA winapi 0.3 is a rather significant overhaul and it's not done yet so there's a lot of code that is inaccessible at the moment.

**Comment by application-developer-DA** [comment]
@retep998 have you had a chance to look on the changes? If you have any remarks, please inform me, so I can do the appropriate changes.

**Pull request merged**
