### PR TITLE
Add bindings for `setupapi`

### PR DESCRIPTION
**Pull request by trlim**
`setupapi` and its dependent header `spapidef` are updated for 0.3.
This also includes `devguid` which is required to use some `setupapi` functions.

### CODE REVIEW

**Comment by trlim** [comment]
Don't know why travis fails to build for nightly.

**Comment by retep998** [comment]
Travis failure is due to https://github.com/rust-lang/rust/issues/37786

**Comment by retep998** [comment]
Appveyor failure is due to https://github.com/rust-lang/cargo/issues/3384

**Comment by trlim** [comment]
Found some function signatures are wrong and realized some definitions are not fully following guidelines.
I added two commits to fix that.

**Pull request merged**
