### PR TITLE
Add missing mod statement for securitybaseapi

### PR DESCRIPTION
**Pull request by CasualX**
Title

Cargo.toml and build.rs seem to reference it.

I'm not sure how to test that this will actually fix the problem, but this seems like the obvious fix.

### CODE REVIEW

**Comment by retep998** [comment]
@GuillaumeGomez Shouldn't the tests detect this sort of stuff?

**Comment by GuillaumeGomez** [comment]
It's supposed to, yes.

**Comment by CasualX** [comment]
Is there anything that needs to happen for this to be merged?

**Comment by GuillaumeGomez** [comment]
For me to fix the test I assume. Will do it this week-end if I don't forget. :)

**Comment by GuillaumeGomez** [comment]
Solved in #568. Once merged, your PR will be able to be merged as well.

**Comment by CasualX** [comment]
Cool, glad I was able to contribute 👍

**Pull request merged**
