### PR TITLE
TOUCHINPUT struct. Related constants and functions.

### PR DESCRIPTION
**Pull request by cpardotortosa**

### CODE REVIEW

**Comment by cpardotortosa** [comment]
I don't really know what to do about the failed check. Any hint?  Thank you.

**Comment by retep998** [comment]
That was https://github.com/rust-lang/rust/issues/31840 which should be fixed by now. I've started a new build which should work.

**Comment by Eh2406** [comment]
check still "Waiting for status to be reported"... What dose it need to be happy?

**Comment by retep998** [comment]
Oh, I have github set to only accept changes to master after they've been tested on a branch, but appveyor/branch doesn't run on other people's branches, only PRs. So don't mind it, the two pr checks passed and that is what matters.

**Comment by retep998** [comment]
https://github.com/retep998/winapi-rs/commit/2d2c2d27ee9059590d901c0c5bcca08b591fd0ad already landed into master but that extra merge commit you had tacked on made github think this wasn't merged, so closing because this is actually merged.

**Pull request closed without merging**
