### PR TITLE
Added GetSecurityInfo

### PR DESCRIPTION
**Pull request by nils-tekampe**

### CODE REVIEW

**Comment by retep998** [comment]
In Rust the parameter name is supposed to go _before_ the parameter type.

**Comment by retep998** [comment]
You appear to have accidentally run rustfmt.

**Comment by nils-tekampe** [comment]
Sorry, that is the configuration of my editor ;-) 
Can you please close this PR and I'll open a new one?! I guess that would be the best way to handle this.

**Comment by retep998** [comment]
You can also rewrite history and force push instead of creating a new PR. You should have the ability to close your own PR though if you do decide to create a new PR.

**Pull request closed without merging**
