### PR TITLE
Move all bcrypt functions to shared

### PR DESCRIPTION
**Pull request by kichristensen**

### CODE REVIEW

**Comment by retep998** [comment]
There is no `bcrypt.h` in `um` in the Windows SDK.

**Comment by kichristensen** [comment]
Sorry, it is in shared, I'll fix it

**Comment by Susurrus** [comment]
@kichristensen Looks like you have `winnt` as a required feature but it's not actually used. Probably just need to remove it.

**Comment by Susurrus** [comment]
@kichristensen Also, like your other commit, the function declaration order isn't correct. You should follow the same order as they are listed in the Windows header file.

**Comment by Susurrus** [comment]
This is unnecessary now that #459 was merged, yes?

**Pull request closed without merging**
