### PR TITLE
Updated subcrate links

### PR DESCRIPTION
**Pull request by Aaronepower**

### CODE REVIEW

**Comment by retep998** [comment]
Are you sure that is correct?
I see documentation at https://retep998.github.io/doc/kernel32/index.html

**Comment by Aaronepower** [comment]
@retep998 Look at the list of crates. of the side, that isn't the full list of sub crates. I found this out by going to `xinput` and getting a 404 on the documentation link.

**Comment by retep998** [comment]
@Aaronepower Sure, that's just because I never uploaded documentation for them yet. Also I am incapable of uploading documentation for all crates due to https://github.com/rust-lang/cargo/issues/1241

**Comment by Aaronepower** [comment]
@retep998 But isn't https://retep998.github.io/doc/winapi/xinput/index.html the crate documentation? And those crates on the side like kernel32 need to be updated.

**Comment by retep998** [comment]
@Aaronepower That isn't the documentation for the crate. That is in fact the documentation for the module inside winapi. The `xinput` crate covers functions from `xinput.lib`. The `xinput` module in `winapi` covers types/constants defined in `xinput.h`.

**Comment by Aaronepower** [comment]
@retep998 Ah, my mistake then.

**Pull request closed without merging**
