### PR TITLE
Add more code style requirements

### PR DESCRIPTION
**Pull request by Susurrus**
Writes down a few of the things we've discussed on gitter.

### CODE REVIEW

**Comment by Susurrus** [comment]
Updated based on comments by @retep998 in #447.

**Comment by Susurrus** [comment]
Also added line wrapping so it's easier to read and edit in a termianl.

**Comment by retep998** [comment]
Conflicts.

**Comment by Susurrus** [comment]
Should be fixed now.

**Comment by Susurrus** [comment]
@retep998 This should be all clear to merge. Just wanted to ping you on this since it's a minor PR that should help contributors on future PRs.

**Comment by Susurrus** [comment]
Looks like you manually added a lot of stuff that this covered here, so it's no longer necessary.

**Pull request closed without merging**
