### PR TITLE
Add IShellFolder and IShellFolder2

### PR DESCRIPTION
**Pull request by ArturKovacs**
This PR adds um::shobjidl_core::{IEnumIDList, IShellFolder, IShellFolder2, IEnumExtraSearch} and types and constants related to them.

### CODE REVIEW

**Comment by ArturKovacs** [comment]
If I'm not mistaken, the nightly failing is unrelated to the changes in this PR. However the 1.6.0 channel failing is absolutely related and unfortunatley STRRET cannot be supported without a way to specify a packing of 8. 

The first release of Rust that supports this feature is 1.33.0 (see https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1330-2019-02-28). Can we increase the minimal required version for this crate? (Please don't get angry at me 🐰)

**Comment by retep998** [comment]
The required minimal version will be increased in winapi 0.4.

**Comment by ArturKovacs** [comment]
I'd like to add `IContextMenu` as well. Can I add commits that add new items or should I open another PR for things unrelated to the original content of the current PR?

**Comment by ArturKovacs** [comment]
Every addition that this PR contains is also contained in #834 so I'll just close this.

**Pull request closed without merging**
