### PR TITLE
Port some more libraries to 0.3

### PR DESCRIPTION
**Pull request by Susurrus**
Another small set of libraries ported to 0.3.

### CODE REVIEW

**Comment by Susurrus** [comment]
Alright, tests pass on this. Should be ready to merge.

**Comment by Susurrus** [comment]
This one's pretty small, @retep998 any way you could review this sometime soon?

**Comment by retep998** [comment]
@Susurrus I'll get around to it when I'm done with what I'm working on.

**Comment by Susurrus** [comment]
Great, thanks!

**Pull request merged**
