### PR TITLE
Update libraries for 0.3

### PR DESCRIPTION
**Pull request by schulzch**
This PR does:
- Parse list of libraries from `Cargo.toml` (replaces `LIBS` in `build.rs`).
- Adds more libraries, based on directory names in `lib`

Should be in line with #316.

### CODE REVIEW

**Comment by schulzch** [comment]
CI errors are weird (missing libraries on gcc and unknown error for rust 1.0)

**Comment by retep998** [comment]
`toml` depends on `serde` which I believe at some point released a version which could not be parsed by older Cargo. Therefore `toml` would significantly raise the minimum Rust requirement for winapi which I do not want to do at this time. Also I don't like depending on external crates anyway (they'll steal all my downloads!).

**Comment by schulzch** [comment]
Ok, I'll remove that part.

I've been playing around with using `bindgen` on `windows.h` and it works okay-ish, except for cast-style constants like `#define SOME_CONST ((int) 3)`. I'll push it later on. What are your thoughts on automation in general?

**Comment by retep998** [comment]
I don't mind people using bindgen to help them write winapi bindings as long as the end result is accurate and in the correct style.

**Comment by schulzch** [comment]
Done. CI issue seems to be related to AppVeyor (missing libraries).

In case you are interested in experiments with ´rustgen` see [winapi-gen-rs](https://github.com/schulzch/winapi-gen-rs).

**Comment by retep998** [comment]
PR has rather major conflicts.

**Comment by retep998** [comment]
This PR basically has no point anymore given the way that library dependencies are now handled.

**Pull request closed without merging**
