### PR TITLE
Add kernel32 functions

### PR DESCRIPTION
**Pull request by skdltmxn**
Added most functions of kernel32 and related structures.

### CODE REVIEW

**Comment by retep998** [comment]
What is with these warnings?
```
src\winnt.rs:2062:5: 2062:34 warning: variant is never used: `UmsThreadInvalidInfoClass`, #[warn(dead_code)] on by default 
src\winnt.rs:2062     UmsThreadInvalidInfoClass = 0, 
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src\winnt.rs:2063:5: 2063:25 warning: variant is never used: `UmsThreadUserContext`, #[warn(dead_code)] on by default 
src\winnt.rs:2063     UmsThreadUserContext, 
                      ^~~~~~~~~~~~~~~~~~~~
src\winnt.rs:2064:5: 2064:22 warning: variant is never used: `UmsThreadPriority`, #[warn(dead_code)] on by default 
src\winnt.rs:2064     UmsThreadPriority,              // Reserved 
                      ^~~~~~~~~~~~~~~~~
src\winnt.rs:2065:5: 2065:22 warning: variant is never used: `UmsThreadAffinity`, #[warn(dead_code)] on by default 
src\winnt.rs:2065     UmsThreadAffinity,              // Reserved 
                      ^~~~~~~~~~~~~~~~~
src\winnt.rs:2066:5: 2066:17 warning: variant is never used: `UmsThreadTeb`, #[warn(dead_code)] on by default 
src\winnt.rs:2066     UmsThreadTeb, 
                      ^~~~~~~~~~~~
src\winnt.rs:2067:5: 2067:25 warning: variant is never used: `UmsThreadIsSuspended`, #[warn(dead_code)] on by default 
src\winnt.rs:2067     UmsThreadIsSuspended, 
                      ^~~~~~~~~~~~~~~~~~~~
src\winnt.rs:2068:5: 2068:26 warning: variant is never used: `UmsThreadIsTerminated`, #[warn(dead_code)] on by default 
src\winnt.rs:2068     UmsThreadIsTerminated, 
                      ^~~~~~~~~~~~~~~~~~~~~
src\winnt.rs:2069:5: 2069:26 warning: variant is never used: `UmsThreadMaxInfoClass`, #[warn(dead_code)] on by default 
src\winnt.rs:2069     UmsThreadMaxInfoClass, 
                      ^~~~~~~~~~~~~~~~~~~~~
```

**Comment by skdltmxn** [comment]
Resolved warnings: they were due to x64 only APIs.

**Comment by skdltmxn** [comment]
Do I have to rebase this PR?

**Comment by retep998** [comment]
The easiest way to rebase is `git pull --rebase origin master` where origin is this repo. If there any conflicts, use some sort of merge tool on the conflicted files, or just edit them manually. Once you've fixed the conflicts, stage the conflicted files to the commit, and then `git rebase --continue`.

**Comment by skdltmxn** [comment]
OK, I think it's rebased right.
But why is Appveyor suddenly giving *lots* of warning?

**Comment by skdltmxn** [comment]
I made a new PR resolving those warnings.

**Pull request merged**
