### PR TITLE
Updated various modules to 0.3

### PR DESCRIPTION
**Pull request by brashaw**
Refer to the commits.

### CODE REVIEW

**Comment by retep998** [comment]
Build is failing.

**Comment by retep998** [comment]
CI is still failing.

**Comment by brashaw** [comment]
Yep, I'm on it.

**Comment by retep998** [comment]
Still failing...

**Comment by brashaw** [comment]
Ok actually I think I see what the problem is here... I was setting the target but I'm on the wrong toolchain.

**Comment by retep998** [comment]
Could you squash everything together into one commit?

**Comment by brashaw** [comment]
I've never used squash so I'll have to learn it real quick. If you don't want to wait, I think Github allows you to "squash & merge" a PR.

**Comment by retep998** [comment]
Learning how to rebase will probably take you a while. I'll just squash it myself.

**Comment by brashaw** [comment]
Thanks. I'll learn rebasing and squashing before my next PR.

**Comment by retep998** [comment]
Landed as https://github.com/retep998/winapi-rs/commit/296b2461f7ffeaca48fadd2f263cad0d4098f844

**Pull request closed without merging**
