### PR TITLE
Add um::synchapi

### PR DESCRIPTION
**Pull request by Popog**
Should be everything in synchapi.rs (some missing dependencies currently commented out).

### CODE REVIEW

**Comment by retep998** [comment]
Did you forget to actually check in the new `synchapi`?

**Comment by Popog** [comment]
........... Worse, GitExtensions swallowed the file and deleted it..... great.......

**Comment by Popog** [comment]
HAHA, got it back! Uninstalling GitExtensions forever now.

**Comment by Popog** [comment]
Found some mistakes I made. I'm gonna hold off on this, give it another couple looks and probably resubmit this next weekend.

**Pull request closed without merging**
