### PR TITLE
Migrate shcore functions to 0.3

### PR DESCRIPTION
**Pull request by Susurrus**
This currently fails because of issues with `shcore` not being exposed as a library. @retep998 seems to understand the complete issue, so this PR is pending resolving that library.

### CODE REVIEW

**Comment by retep998** [comment]
I've added the rest of the import libraries for MinGW targets: https://github.com/retep998/winapi-rs/commit/f628c80106e97516e8031880995727b7a14d6615

**Comment by Susurrus** [comment]
Then let's run it again and see what we get!

**Comment by Susurrus** [comment]
Hot-diggity-damn it worked!

**Comment by Susurrus** [comment]
I ran it without rebasing and it worked, which is interesting. This one is properly rebased, but it should still work if the last one did.

**Comment by retep998** [comment]
I believe on PRs appveyor actually tests the result of merging the PR onto the target branch.

**Comment by Susurrus** [comment]
Interesting, didn't know that! I've used bors and homu to solve that problem, didn't realize it.

So does this look good to merge? This is a relatively small one here!

**Pull request merged**
