### PR TITLE
Migrate dxva2 APIs

### LINKED ISSUE #503: Monitor Configuration API
The [Monitor configuration functions](https://msdn.microsoft.com/en-us/library/windows/desktop/dd692964(v=vs.85).aspx) (both in dxva2 and the internal DDC/CI variants from gdi32) do not seem to be supported. I may try to figure out how to do it myself but for now consider this a feature request!

### PR DESCRIPTION
**Pull request by skdltmxn**
This PR resolves #503

### CODE REVIEW

**Comment by docbrown** [comment]
highlevelmonitorconfigurationapi
    lowlevelmonitorconfigurationapi
    physicalmonitorenumerationapi

Good grief, Microsoft.

**Comment by skdltmxn** [comment]
What's wrong with AppVeyor?

**Comment by retep998** [comment]
There's a merge conflict still, so it can't test it.

**Comment by skdltmxn** [comment]
Weird... resolved them anyway.

**Comment by arcnmx** [comment]
Is there anything that needs to be done to help move this along?

**Pull request merged**
