### PR TITLE
Add iphlpapi support

### PR DESCRIPTION
**Pull request by LuoZijun**
Issue: https://github.com/retep998/winapi-rs/issues/561

Files:

C Header          |                 Rust                    | Review
----------------- | --------------------------------------- | --------
[shared/ifdef.h](https://github.com/LuoZijun/WindowsSDK/tree/master/10.0.16299.0/shared/ifdef.h)         | [shared/ifdef.rs](https://github.com/LuoZijun/winapi-rs/blob/iphlpapi/src/shared/ifdef.rs)         | TODO
[shared/ifmib.h](https://github.com/LuoZijun/WindowsSDK/tree/master/10.0.16299.0/shared/ifmib.h)         | [shared/ifmib.rs](https://github.com/LuoZijun/winapi-rs/blob/iphlpapi/src/shared/ifmib.rs)         | TODO
[shared/ipifcons.h](https://github.com/LuoZijun/WindowsSDK/tree/master/10.0.16299.0/shared/ipifcons.h)   | [shared/ipifcons.rs](https://github.com/LuoZijun/winapi-rs/blob/iphlpapi/src/shared/ipifcons.rs)   | TODO
[shared/ipmib.h](https://github.com/LuoZijun/WindowsSDK/tree/master/10.0.16299.0/shared/ipmib.h)         | [shared/ipmib.rs](https://github.com/LuoZijun/winapi-rs/blob/iphlpapi/src/shared/ipmib.rs)         | TODO
[shared/Iprtrmib.h](https://github.com/LuoZijun/WindowsSDK/tree/master/10.0.16299.0/shared/Iprtrmib.h)   | [shared/iprtrmib.rs](https://github.com/LuoZijun/winapi-rs/blob/iphlpapi/src/shared/iprtrmib.rs)   | TODO
[shared/mprapidef.h](https://github.com/LuoZijun/WindowsSDK/tree/master/10.0.16299.0/shared/mprapidef.h) | [shared/mprapidef.rs](https://github.com/LuoZijun/winapi-rs/blob/iphlpapi/src/shared/mprapidef.rs) | TODO
[shared/nldef.h](https://github.com/LuoZijun/WindowsSDK/tree/master/10.0.16299.0/shared/nldef.h)         | [shared/nldef.rs](https://github.com/LuoZijun/winapi-rs/blob/iphlpapi/src/shared/nldef.rs)         | TODO
[shared/tcpestats.h](https://github.com/LuoZijun/WindowsSDK/tree/master/10.0.16299.0/shared/tcpestats.h) | [shared/tcpestats.rs](https://github.com/LuoZijun/winapi-rs/blob/iphlpapi/src/shared/tcpestats.rs) | TODO
[shared/tcpmib.h](https://github.com/LuoZijun/WindowsSDK/tree/master/10.0.16299.0/shared/tcpmib.h)       | [shared/tcpmib.rs](https://github.com/LuoZijun/winapi-rs/blob/iphlpapi/src/shared/tcpmib.rs)       | TODO
[shared/udpmib.h](https://github.com/LuoZijun/WindowsSDK/tree/master/10.0.16299.0/shared/udpmib.h)       | [shared/udpmib.rs](https://github.com/LuoZijun/winapi-rs/blob/iphlpapi/src/shared/udpmib.rs)       | TODO
[um/IPExport.h](https://github.com/LuoZijun/WindowsSDK/tree/master/10.0.16299.0/um/IPExport.h)           | [um/ipexport.rs](https://github.com/LuoZijun/winapi-rs/blob/iphlpapi/src/um/ipexport.rs)           | TODO
[um/IPTypes.h](https://github.com/LuoZijun/WindowsSDK/tree/master/10.0.16299.0/um/IPTypes.h)             | [um/iptypes.rs](https://github.com/LuoZijun/winapi-rs/blob/iphlpapi/src/um/iptypes.rs)             | TODO
[um/iphlpapi.h](https://github.com/LuoZijun/WindowsSDK/tree/master/10.0.16299.0/um/iphlpapi.h)           | [um/iphlpapi.rs](https://github.com/LuoZijun/winapi-rs/blob/iphlpapi/src/um/iphlpapi.rs)           | TODO

Stage:

- [ ] Dependency Tree ( `build.rs` )
- [ ] Header Translation
- [ ] Code Style

### CODE REVIEW

**Comment by LuoZijun** [comment]
@retep998 I know this PR have many code style problem, i hope we can put it in the final stage to solve it.

**Review by brooss — COMMENTED** [review]
time_t is 32bits on x86

**Comment by retep998** [comment]
@brooss `time_t` is 64bit on x86.

**Comment by brooss** [comment]
Ok, possibly I'm wrong, but from my testing of `GetAdapterAddresses()` `IP_ADAPTER_INFO.LeaseObtained` and `IP_ADAPTER_INFO.LeaseExpires` are 32bit on x86 and 64bit on x86_64.

**Comment by retep998** [comment]
How exactly were you testing that? VC++ by default uses a 64bit `time_t` on 32bit. It is possible to get a 32-bit `time_t` by defining a certain macro, but that's a non-default configuration which I don't support. I don't know what MinGW does.

**Comment by brooss** [comment]
I'm testing from Rust. Call GetAdaptersInfo() with a zero sized buffer and:

> GetAdaptersInfo fills in this variable with the required size, and returns an error code of ERROR_BUFFER_OVERFLOW.

`let mut buflen: ULONG = unsafe{mem::zeroed()};`
`let _ = unsafe{GetAdaptersInfo(null_mut(), &mut buflen)};`
 
buflen should then be a multiple of `mem::sizeof::<IP_ADAPTER_INFO>()`. 

I get multiples of 640bytes returned by `GetAdaptersInfo` on x86.

If `time_t` is 32bit then `sizeof::<IP_ADAPTER_INFO>()` is 640bytes and the Lease times look correct to me. If time_t is 64bit then the `sizeof::<IP_ADAPTER_INFO>()` is 8bytes too long, LeaseObtained has a nonsense time and LeaseExpires is zero.

Just checked on mingw32 and `sizeof (IP_ADAPTER_INFO);` also shows 640 bytes.

What does sizeof (IP_ADAPTER_INFO); give on vc++?

**Comment by retep998** [comment]
`sizeof(IP_ADAPTER_INFO)` in VC++ is 648, but `GetAdaptersInfo` specifies a value that is a multiple of 640 for me as well. If I call the function with a large enough buffer, then the `Next` field points to an address that is 640 bytes after the base address.

Also [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366062) has this to say:
>When using Visual Studio 2005 and later, the time_t datatype defaults to an 8-byte datatype, not the 4-byte datatype used for the LeaseObtained and LeaseExpires members on a 32-bit platform. To properly use the IP_ADAPTER_INFO structure on a 32-bit platform, define _USE_32BIT_TIME_T (use -D _USE_32BIT_TIME_T as an option, for example) when compiling the application to force the time_t datatype to a 4-byte datatype.

So while `time_t` itself should remain 64bit, `IP_ADAPTER_INFO` should probably use `__time32_t`.

**Comment by brooss** [comment]
> So while `time_t` itself should remain 64bit, `IP_ADAPTER_INFO` should probably use __time32_t.

:+1:

**Comment by crmaxx** [comment]
@LuoZijun on current nightly I have next issue
```
$ cargo build
   Compiling winapi v0.3.4 (https://github.com/LuoZijun/winapi-rs?branch=iphlpapi#9dddf9d6)
error: no rules expected the token `Value`
  --> C:\Users\mzhukov\.cargo\git\checkouts\winapi-rs-3464f7d97049bddf\9dddf9d\src\shared\ifdef.rs:79:5
   |
79 |     Value: ULONG64,
   |     ^^^^^

error: no rules expected the token `ullAlign`
   --> C:\Users\mzhukov\.cargo\git\checkouts\winapi-rs-3464f7d97049bddf\9dddf9d\src\shared\iprtrmib.rs:152:5
    |
152 |     ullAlign: ULONGLONG,
    |     ^^^^^^^^

error: no rules expected the token `s`
  --> C:\Users\mzhukov\.cargo\git\checkouts\winapi-rs-3464f7d97049bddf\9dddf9d\src\shared\udpmib.rs:52:5
   |
52 |     s: c_int,
   |     ^

error: no rules expected the token `s`
   --> C:\Users\mzhukov\.cargo\git\checkouts\winapi-rs-3464f7d97049bddf\9dddf9d\src\shared\udpmib.rs:103:5
    |
103 |     s: c_int,
    |     ^

error: aborting due to 4 previous errors

error: Could not compile `winapi`.
```

**Comment by LuoZijun** [comment]
@crmaxx 

Yeah, I guess this is an anonymous macro problem.
It seems that anonymous structure members should use `BITFIELD!(` not `BITFIELD!{`.
@retep998 Am i right ?

I developed it on macOS, so fixing the problem took me some time.
I will try to fix that on this weekend.

**Comment by retep998** [comment]
@LuoZijun According to `CONTRIBUTING.md`

>Macro invocations at the item level should use `{}`. Macro invocations at the expression level should use `()`.

Since `BITFIELD!` is invoked at the item level...

**Comment by LuoZijun** [comment]
@retep998 Thank you, got it.

**Comment by awakecoding** [comment]
Any update on this? We would need the same API

**Comment by devnought** [comment]
Like @awakecoding, also looking to use this. Any updates? @LuoZijun ?

**Comment by glebpom** [comment]
Hi! Is it going to be merged? Is any help needed?

**Comment by retep998** [comment]
There is still some work done that needs to be done with this PR before it can be merged, but it appears the original author of this PR has abandoned it, so anyone is free to resume work on this PR.

**Comment by mattlknight** [comment]
@retep998 I would like to take ownership of this, or at least, help complete this PR. That being said, I am very noob when it comes to FFI stuff. I'm working on gettting this completed in my local fork now, contuining where @LuoZijun left off. Trying to figure out the output of "cargo test" now.

**Comment by mattlknight** [comment]
@awakecoding @devnought @glebpom I have opened a new PR #675 for this and continued where @LuoZijun left off. Any comments/critiques welcome. I'm now checking to see what is missing, if anything, otherwise the PR is done.

**Comment by retep998** [comment]
This PR has been superseded by https://github.com/retep998/winapi-rs/pull/802

**Pull request closed without merging**
