### PR TITLE
Add netapi32 support

### PR DESCRIPTION
**Pull request by skdltmxn**

### CODE REVIEW

**Comment by retep998** [comment]
Do you think you could use the new `ENUM!` and `FLAGS!` macros for your enums?

**Comment by skdltmxn** [comment]
It looks like ENUM! and FLAGS! both require every entry of the enum to have specific value.
How can I use those macros for enums without any values?

**Comment by retep998** [comment]
The value of each enum variant is just the previous + 1, and the first, if not specified, is 0. Making the macro handle that automatically would involve macro recursion and that's a bit beyond my current abilities with macros.

**Comment by retep998** [comment]
Actually, with a bit of help, I managed to improve the `ENUM!` macro to be able to calculate implicit values for the variants. `FLAGS!` still needs explicit values, but that's okay since the variants are powers of two, not sequential integers, and C doesn't implicitly do that either.

**Comment by skdltmxn** [comment]
I replaced my enums with ENUM! macro.

**Pull request merged**
