### PR TITLE
Finish porting dxguid to winapi 0.3

### PR DESCRIPTION
**Pull request by Susurrus**
Review after #488.

### CODE REVIEW

**Comment by Susurrus** [comment]
Hmm, not certain why this failed based on the CI error messsages. @retep998 Any idea?

**Comment by Arnavion** [comment]
```
error: failed to run custom build command for `winapi v0.3.0-alpha.0 (file:///C:/Stuff/Sources/winapi-rs)`
process didn't exit successfully: `C:\Stuff\Sources\winapi-rs\target\debug\build\winapi-e639dacfaa8bde63\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at '', src\libcore\option.rs:819:4
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:380
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:397
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:611
   4: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:572
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:522
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:498
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   8: core::option::expect_failed
             at C:\projects\rust\src\libcore\option.rs:819
   9: core::option::Option<build_script_build::Header*>::expect<build_script_build::Header*>
             at C:\projects\rust\src\libcore\option.rs:302
  10: build_script_build::Graph::resolve_dependencies
             at .\build.rs:323
  11: build_script_build::try_everything
             at .\build.rs:355
  12: build_script_build::main
             at .\build.rs:363
  13: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  14: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:54
  15: main
  16: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  17: **BaseThreadInitThunk**
```

**Comment by Susurrus** [comment]
Thanks, @Arnavion, build passes now!

**Comment by Susurrus** [comment]
@retep998 ping!

**Comment by Susurrus** [comment]
Aww, yeah! Thanks!

**Pull request merged**
