### PR TITLE
Update cargo.toml for 0.3.7 release

### LINKED ISSUE #727: rav1e: winapi does not compile to aarch64-pc-windows-msvc target
When running `cargo build --release --target=aarch64-pc-windows-msvc` winapi-rs doesn't compile. Is there something I need to update or configure differently, or is this a bug?

Full log: https://ci.appveyor.com/project/EwoutH/rav1e/builds/21624989/job/anr30v88gfie2cx5

```
error[E0432]: unresolved import `um::winnt::PIMAGE_NT_HEADERS`
  --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\dbghelp.rs:14:55
   |
14 |     BOOLEAN, CHAR, HANDLE, LIST_ENTRY, PCSTR, PCWSTR, PIMAGE_NT_HEADERS, PIMAGE_SECTION_HEADER,
   |                                                       ^^^^^^^^^^^^^^^^^ no `PIMAGE_NT_HEADERS` in `um::winnt`. Did you mean to use `PIMAGE_NT_HEADERS64`?
error[E0432]: unresolved import `um::winnt::PCONTEXT`
  --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\errhandlingapi.rs:11:48
   |
11 |     EXCEPTION_POINTERS, LONG, LPCSTR, LPCWSTR, PCONTEXT, PEXCEPTION_RECORD,
   |                                                ^^^^^^^^ no `PCONTEXT` in `um::winnt`
error[E0432]: unresolved import `um::winnt::PCONTEXT`
  --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\minwinbase.rs:22:52
   |
22 |     CHAR, EXCEPTION_RECORD, HANDLE, LPSTR, LPWSTR, PCONTEXT, PRTL_CRITICAL_SECTION,
   |                                                    ^^^^^^^^ no `PCONTEXT` in `um::winnt`
error[E0432]: unresolved import `um::winnt::CONTEXT`
  --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\processthreadsapi.rs:16:5
   |
16 |     CONTEXT, HANDLE, LPCSTR, LPCWSTR, LPSTR, LPWSTR, PAPCFUNC, PHANDLE, PPROCESSOR_NUMBER,
   |     ^^^^^^^ no `CONTEXT` in `um::winnt`
error[E0432]: unresolved import `um::winnt::PCONTEXT`
  --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winbase.rs:33:59
   |
33 |     LPOSVERSIONINFOEXW, LPSTR, LPWSTR, MAXLONG, PBOOLEAN, PCONTEXT, PCWSTR, PFIRMWARE_TYPE,
   |                                                           ^^^^^^^^ no `PCONTEXT` in `um::winnt`
error[E0412]: cannot find type `CM_NOTIFY_FILTER_u` in this scope
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\cfgmgr32.rs:651:14
    |
651 | UNION!{union CM_NOTIFY_FILTER_u {
    |              ^^^^^^^^^^^^^^^^^^ help: a struct with a similar name exists: `CM_NOTIFY_FILTER`
error[E0412]: cannot find type `CM_NOTIFY_FILTER_u` in this scope
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\cfgmgr32.rs:662:8
    |
662 |     u: CM_NOTIFY_FILTER_u,
    |        ^^^^^^^^^^^^^^^^^^ help: a struct with a similar name exists: `CM_NOTIFY_FILTER`
error[E0412]: cannot find type `LPSTACKFRAME` in this scope
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\dbghelp.rs:469:21
    |
469 |         StackFrame: LPSTACKFRAME,
    |                     ^^^^^^^^^^^^ help: a type alias with a similar name exists: `LPSTACKFRAME64`
error[E0412]: cannot find type `PREAD_PROCESS_MEMORY_ROUTINE` in this scope
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\dbghelp.rs:471:28
    |
471 |         ReadMemoryRoutine: PREAD_PROCESS_MEMORY_ROUTINE,
    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a type alias with a similar name exists: `PREAD_PROCESS_MEMORY_ROUTINE64`
error[E0412]: cannot find type `PFUNCTION_TABLE_ACCESS_ROUTINE` in this scope
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\dbghelp.rs:472:37
    |
472 |         FunctionTableAccessRoutine: PFUNCTION_TABLE_ACCESS_ROUTINE,
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a type alias with a similar name exists: `PFUNCTION_TABLE_ACCESS_ROUTINE64`
error[E0412]: cannot find type `PGET_MODULE_BASE_ROUTINE` in this scope
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\dbghelp.rs:473:31
    |
473 |         GetModuleBaseRoutine: PGET_MODULE_BASE_ROUTINE,
    |                               ^^^^^^^^^^^^^^^^^^^^^^^^ help: a type alias with a similar name exists: `PGET_MODULE_BASE_ROUTINE64`
error[E0412]: cannot find type `PTRANSLATE_ADDRESS_ROUTINE` in this scope
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\dbghelp.rs:474:27
    |
474 |         TranslateAddress: PTRANSLATE_ADDRESS_ROUTINE,
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a type alias with a similar name exists: `PTRANSLATE_ADDRESS_ROUTINE64`
error[E0412]: cannot find type `OVERLAPPED_u` in this scope
  --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\minwinbase.rs:40:14
   |
40 | UNION!{union OVERLAPPED_u {
   |              ^^^^^^^^^^^^ help: a struct with a similar name exists: `OVERLAPPED`
error[E0412]: cannot find type `OVERLAPPED_u` in this scope
  --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\minwinbase.rs:48:8
   |
48 |     u: OVERLAPPED_u,
   |        ^^^^^^^^^^^^ help: a struct with a similar name exists: `OVERLAPPED`
error[E0412]: cannot find type `PROCESS_HEAP_ENTRY_u` in this scope
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\minwinbase.rs:166:14
    |
166 | UNION!{union PROCESS_HEAP_ENTRY_u {
    |              ^^^^^^^^^^^^^^^^^^^^ help: a struct with a similar name exists: `PROCESS_HEAP_ENTRY`
error[E0412]: cannot find type `PROCESS_HEAP_ENTRY_u` in this scope
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\minwinbase.rs:177:8
    |
177 |     u: PROCESS_HEAP_ENTRY_u,
    |        ^^^^^^^^^^^^^^^^^^^^ help: a struct with a similar name exists: `PROCESS_HEAP_ENTRY`
error[E0412]: cannot find type `REASON_CONTEXT_Reason` in this scope
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\minwinbase.rs:193:14
    |
193 | UNION!{union REASON_CONTEXT_Reason {
    |              ^^^^^^^^^^^^^^^^^^^^^ help: a struct with a similar name exists: `REASON_CONTEXT_Detailed`
error[E0412]: cannot find type `REASON_CONTEXT_Reason` in this scope
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\minwinbase.rs:201:13
    |
201 |     Reason: REASON_CONTEXT_Reason,
    |             ^^^^^^^^^^^^^^^^^^^^^ help: a struct with a similar name exists: `REASON_CONTEXT_Detailed`
error[E0412]: cannot find type `DEBUG_EVENT_u` in this scope
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\minwinbase.rs:273:14
    |
273 | UNION!{union DEBUG_EVENT_u {
    |              ^^^^^^^^^^^^^ help: a struct with a similar name exists: `DEBUG_EVENT`
error[E0412]: cannot find type `DEBUG_EVENT_u` in this scope
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\minwinbase.rs:289:8
    |
289 |     u: DEBUG_EVENT_u,
    |        ^^^^^^^^^^^^^ help: a struct with a similar name exists: `DEBUG_EVENT`
error[E0412]: cannot find type `LPLDT_ENTRY` in this scope
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winbase.rs:630:26
    |
630 |         lpSelectorEntry: LPLDT_ENTRY,
    |                          ^^^^^^^^^^^ not found in this scope
error[E0412]: cannot find type `COPYFILE2_MESSAGE_Info` in this scope
    --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winbase.rs:1772:14
     |
1772 | UNION!{union COPYFILE2_MESSAGE_Info {
     |              ^^^^^^^^^^^^^^^^^^^^^^ help: a struct with a similar name exists: `COPYFILE2_MESSAGE_Error`
error[E0412]: cannot find type `COPYFILE2_MESSAGE_Info` in this scope
    --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winbase.rs:1784:11
     |
1784 |     Info: COPYFILE2_MESSAGE_Info,
     |           ^^^^^^^^^^^^^^^^^^^^^^ help: a struct with a similar name exists: `COPYFILE2_MESSAGE_Error`
error[E0425]: cannot find value `MAXIMUM_PROC_PER_GROUP` in this scope
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winnt.rs:118:38
    |
118 | pub const MAXIMUM_PROCESSORS: BYTE = MAXIMUM_PROC_PER_GROUP;
    |                                      ^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
help: possible candidate is found in another module, you can import it into scope
    |
9   | use shared::ntdef::MAXIMUM_PROC_PER_GROUP;
    |
error[E0412]: cannot find type `CONTEXT` in this scope
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winnt.rs:223:25
    |
223 |     ContextRecord: *mut CONTEXT,
    |                         ^^^^^^^ not found in this scope
error[E0412]: cannot find type `XSAVE_FORMAT` in this scope
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winnt.rs:955:31
    |
955 | pub type PXSAVE_FORMAT = *mut XSAVE_FORMAT;
    |                               ^^^^^^^^^^^^ help: a type alias with a similar name exists: `PXSAVE_FORMAT`
error[E0412]: cannot find type `XSAVE_FORMAT` in this scope
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winnt.rs:963:18
    |
963 |     LegacyState: XSAVE_FORMAT,
    |                  ^^^^^^^^^^^^ help: a type alias with a similar name exists: `PXSAVE_FORMAT`
error[E0412]: cannot find type `XSTATE_CONTEXT` in this scope
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winnt.rs:985:33
    |
985 | pub type PXSTATE_CONTEXT = *mut XSTATE_CONTEXT;
    |                                 ^^^^^^^^^^^^^^ help: a type alias with a similar name exists: `PXSTATE_CONTEXT`
error[E0412]: cannot find type `PCONTEXT` in this scope
    --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winnt.rs:1454:20
     |
1454 |     ContextRecord: PCONTEXT,
     |                    ^^^^^^^^ not found in this scope
error[E0412]: cannot find type `SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX_u` in this scope
    --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winnt.rs:3558:14
     |
3558 | UNION!{union SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX_u {
     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a struct with a similar name exists: `SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX`
error[E0412]: cannot find type `SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX_u` in this scope
    --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winnt.rs:3568:8
     |
3568 |     u: SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX_u,
     |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a struct with a similar name exists: `SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX`
error[E0412]: cannot find type `PCONTEXT` in this scope
    --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winnt.rs:6975:24
     |
6975 |         ContextRecord: PCONTEXT,
     |                        ^^^^^^^^ not found in this scope
error[E0412]: cannot find type `PSLIST_HEADER` in this scope
    --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winnt.rs:7108:19
     |
7108 |         ListHead: PSLIST_HEADER,
     |                   ^^^^^^^^^^^^^ not found in this scope
error[E0412]: cannot find type `SLIST_HEADER` in this scope
    --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winnt.rs:7111:26
     |
7111 |         ListHead: *const SLIST_HEADER,
     |                          ^^^^^^^^^^^^ not found in this scope
error[E0412]: cannot find type `PSLIST_HEADER` in this scope
    --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winnt.rs:7114:19
     |
7114 |         ListHead: PSLIST_HEADER,
     |                   ^^^^^^^^^^^^^ not found in this scope
error[E0412]: cannot find type `PSLIST_HEADER` in this scope
    --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winnt.rs:7117:19
     |
7117 |         ListHead: PSLIST_HEADER,
     |                   ^^^^^^^^^^^^^ not found in this scope
error[E0412]: cannot find type `PSLIST_HEADER` in this scope
    --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winnt.rs:7121:19
     |
7121 |         ListHead: PSLIST_HEADER,
     |                   ^^^^^^^^^^^^^ not found in this scope
error[E0412]: cannot find type `PSLIST_HEADER` in this scope
    --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winnt.rs:7127:19
     |
7127 |         ListHead: PSLIST_HEADER,
     |                   ^^^^^^^^^^^^^ not found in this scope
error[E0412]: cannot find type `PSLIST_HEADER` in this scope
    --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winnt.rs:7130:19
     |
7130 |         ListHead: PSLIST_HEADER,
     |                   ^^^^^^^^^^^^^ not found in this scope
   Compiling quote v0.6.10
error[E0206]: the trait `Copy` may not be implemented for this type
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\macros.rs:302:23
    |
302 |           impl Copy for $name {}
    |                         ^^^^^ type is not a structure or enumeration
    | 
   ::: C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\cfgmgr32.rs:651:1
    |
651 | / UNION!{union CM_NOTIFY_FILTER_u {
652 | |     [u32; 100] [u64; 50],
653 | |     DeviceInterface DeviceInterface_mut: CM_NOTIFY_FILTER_DeviceInterface,
654 | |     DeviceHandle DeviceHandle_mut: CM_NOTIFY_FILTER_DeviceHandle,
655 | |     DeviceInstance DeviceInstance_mut: CM_NOTIFY_FILTER_DeviceInstance,
656 | | }}
    | |__- in this macro invocation
error[E0206]: the trait `Copy` may not be implemented for this type
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\macros.rs:302:23
    |
302 |           impl Copy for $name {}
    |                         ^^^^^ type is not a structure or enumeration
    | 
   ::: C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\minwinbase.rs:40:1
    |
40  | / UNION!{union OVERLAPPED_u {
41  | |     [u32; 2] [u64; 1],
42  | |     s s_mut: OVERLAPPED_u_s,
43  | |     Pointer Pointer_mut: PVOID,
44  | | }}
    | |__- in this macro invocation
error[E0206]: the trait `Copy` may not be implemented for this type
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\macros.rs:302:23
    |
302 |           impl Copy for $name {}
    |                         ^^^^^ type is not a structure or enumeration
    | 
   ::: C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\minwinbase.rs:166:1
    |
166 | / UNION!{union PROCESS_HEAP_ENTRY_u {
167 | |     [u32; 4] [u64; 3],
168 | |     Block Block_mut: PROCESS_HEAP_ENTRY_Block,
169 | |     Region Region_mut: PROCESS_HEAP_ENTRY_Region,
170 | | }}
    | |__- in this macro invocation
error[E0206]: the trait `Copy` may not be implemented for this type
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\macros.rs:302:23
    |
302 |           impl Copy for $name {}
    |                         ^^^^^ type is not a structure or enumeration
    | 
   ::: C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\minwinbase.rs:193:1
    |
193 | / UNION!{union REASON_CONTEXT_Reason {
194 | |     [u32; 4] [u64; 3],
195 | |     Detailed Detailed_mut: REASON_CONTEXT_Detailed,
196 | |     SimpleReasonString SimpleReasonString_mut: LPWSTR,
197 | | }}
    | |__- in this macro invocation
error[E0206]: the trait `Copy` may not be implemented for this type
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\macros.rs:302:23
    |
302 |           impl Copy for $name {}
    |                         ^^^^^ type is not a structure or enumeration
    | 
   ::: C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\minwinbase.rs:273:1
    |
273 | / UNION!{union DEBUG_EVENT_u {
274 | |     [u32; 21] [u64; 20],
275 | |     Exception Exception_mut: EXCEPTION_DEBUG_INFO,
276 | |     CreateThread CreateThread_mut: CREATE_THREAD_DEBUG_INFO,
...   |
283 | |     RipInfo RipInfo_mut: RIP_INFO,
284 | | }}
    | |__- in this macro invocation
error[E0206]: the trait `Copy` may not be implemented for this type
    --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\macros.rs:302:23
     |
302  |           impl Copy for $name {}
     |                         ^^^^^ type is not a structure or enumeration
     | 
    ::: C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winbase.rs:1772:1
     |
1772 | / UNION!{union COPYFILE2_MESSAGE_Info {
1773 | |     [u64; 8] [u64; 9],
1774 | |     ChunkStarted ChunkStarted_mut: COPYFILE2_MESSAGE_ChunkStarted,
1775 | |     ChunkFinished ChunkFinished_mut: COPYFILE2_MESSAGE_ChunkFinished,
...    |
1779 | |     Error Error_mut: COPYFILE2_MESSAGE_Error,
1780 | | }}
     | |__- in this macro invocation
error[E0206]: the trait `Copy` may not be implemented for this type
    --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\macros.rs:302:23
     |
302  |           impl Copy for $name {}
     |                         ^^^^^ type is not a structure or enumeration
     | 
    ::: C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\um\winnt.rs:3558:1
     |
3558 | / UNION!{union SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX_u {
3559 | |     [u32; 17] [u64; 9],
3560 | |     Processor Processor_mut: PROCESSOR_RELATIONSHIP,
3561 | |     NumaNode NumaNode_mut: NUMA_NODE_RELATIONSHIP,
3562 | |     Cache Cache_mut: CACHE_RELATIONSHIP,
3563 | |     Group Group_mut: GROUP_RELATIONSHIP,
3564 | | }}
     | |__- in this macro invocation
error: aborting due to 46 previous errors
Some errors occurred: E0206, E0412, E0425, E0432.
For more information about an error, try `rustc --explain E0206`.
error: Could not compile `winapi`.
warning: build failed, waiting for other jobs to finish...
error: build failed
Command exited with code 101
```

### PR DESCRIPTION
**Pull request by EwoutH**
Should fix #727.

### CODE REVIEW

**Comment by retep998** [comment]
I handle updating the version number and publishing myself after I go through a final testing process of ensuring no reverse dependency was broken by any changes in `winapi`.

**Comment by EwoutH** [comment]
When do you expect to release the next version?

**Comment by EwoutH** [comment]
@retep998 When do you expect to tag release `0.3.7` or `0.4.0`?

**Comment by atouchet** [comment]
@EwoutH winapi 0.3.7 is out now.

**Pull request closed without merging**
