### PR TITLE
use STRUCT! ware it is simple

### PR DESCRIPTION
**Pull request by Eh2406**
used regexp to fined cases ware STRUCT! is simple

### CODE REVIEW

**Comment by retep998** [comment]
ware -> where
fined -> find

**Comment by Eh2406** [comment]
Sorry about the miss spellings.

Is there a category you want me to look at next? struct with #[derive(Copy)] and impl Clone for ... { fn clone(&self) -> ... { *self } }? or enums?

**Comment by retep998** [comment]
Any Rust enums need to be switched over to `ENUM!` or `FLAGS!` as appropriate. That's all I can think of at the moment. I'll deal with the remaining structs myself once I decide how to deal with them.

**Comment by Eh2406** [comment]
Is there an idiot proof way to determine which one to use? If not I can start looking them up one at a time and see how far I get.

**Comment by retep998** [comment]
If the discriminants are powers of two, then it is `FLAGS!`. Otherwise it is likely `ENUM!`.

**Comment by Eh2406** [comment]
most rust `enom`'s are `#[repr(i32)]` the macro uses `u32` is it ok for me to replace? (sorry to be constantly bugging you. I just want to get it right, so as to not make more work fixing my mistakes.)

**Comment by retep998** [comment]
The representation that the macros uses is fine, so feel free to replace all enums with them regardless of what the repr is.

**Pull request merged**
