### PR TITLE
Add symbols for TLS 1.3

### PR DESCRIPTION
**Pull request by mehcode**
See: https://github.com/wine-mirror/wine/blob/c84fa0a2661f2235fac6f3427201fbb3fd8c8028/include/schannel.h#L98-L99

### CODE REVIEW

**Comment by olback** [comment]
@mehcode Do you have a link to the source where you got those values? All I find is https://docs.microsoft.com/en-us/windows/win32/api/schannel/ns-schannel-schannel_cred which does not mention TLS 1.3. (last updated 12/05/2018)

**Comment by retep998** [comment]
Those values exist in the headers that come with the Windows SDK.

**Review by olback — APPROVED** [review]

**Review by retep998 — APPROVED** [review]

**Comment by retep998** [comment]
CI is failing on line length limits.

**Comment by Neustradamus** [comment]
Replaced by:
- https://github.com/retep998/winapi-rs/pull/963

**Comment by Neustradamus** [comment]
Good news rust-native-tls has now the TLS 1.3 support!

Linked to:
- https://github.com/rust-native-tls/rust-native-tls/pull/353
- https://github.com/rust-native-tls/rust-native-tls/pull/291
- https://github.com/rust-native-tls/rust-native-tls/pull/278
- https://github.com/rust-native-tls/rust-native-tls/pull/235
- https://github.com/rust-native-tls/rust-native-tls/pull/159
- https://github.com/rust-native-tls/rust-native-tls/issues/140
- https://github.com/retep998/winapi-rs/pull/963
- https://github.com/retep998/winapi-rs/pull/859
- https://github.com/olback/barium/issues/14
- https://github.com/element-hq/element-x-ios/issues/786
- https://github.com/matrix-org/matrix-rust-sdk/pull/6053
- https://github.com/deltachat/deltachat-ios/issues/1693

**Pull request closed without merging**
