### PR TITLE
Add missing GetFileVersionInfo*Ex* funcs

### PR DESCRIPTION
**Pull request by roblabla**
Add a handful of missing functions from winver.h, namely GetFileVersionInfo(Size)?Ex(W|A), and the associated constant flags.

### CODE REVIEW

**Comment by nico-abram** [comment]
Relevant header code:

winver.h
```
DWORD APIENTRY GetFileVersionInfoSizeExA(_In_ DWORD dwFlags, _In_ LPCSTR lpwstrFilename, _Out_ LPDWORD lpdwHandle);
DWORD APIENTRY GetFileVersionInfoSizeExW(_In_ DWORD dwFlags, _In_ LPCWSTR lpwstrFilename, _Out_ LPDWORD lpdwHandle);

BOOL APIENTRY GetFileVersionInfoExA(_In_ DWORD dwFlags,
                                    _In_ LPCSTR lpwstrFilename,
                                    _Reserved_ DWORD dwHandle,
                                    _In_ DWORD dwLen,
                                    _Out_writes_bytes_(dwLen) LPVOID lpData);
BOOL APIENTRY GetFileVersionInfoExW(_In_ DWORD dwFlags,
                                    _In_ LPCWSTR lpwstrFilename,
                                    _Reserved_ DWORD dwHandle,
                                    _In_ DWORD dwLen,
                                    _Out_writes_bytes_(dwLen) LPVOID lpData);
```

verrsrc.h
```

/* 
    FILE_VER_GET_... flags are for use by 
    GetFileVersionInfoSizeEx
    GetFileVersionInfoExW
*/
#define FILE_VER_GET_LOCALISED  0x01
#define FILE_VER_GET_NEUTRAL    0x02
#define FILE_VER_GET_PREFETCHED 0x04

/* ----- Types and structures ----- */

typedef struct tagVS_FIXEDFILEINFO
{
    DWORD   dwSignature;            /* e.g. 0xfeef04bd */
    DWORD   dwStrucVersion;         /* e.g. 0x00000042 = "0.42" */
    DWORD   dwFileVersionMS;        /* e.g. 0x00030075 = "3.75" */
    DWORD   dwFileVersionLS;        /* e.g. 0x00000031 = "0.31" */
    DWORD   dwProductVersionMS;     /* e.g. 0x00030010 = "3.10" */
    DWORD   dwProductVersionLS;     /* e.g. 0x00000031 = "0.31" */
    DWORD   dwFileFlagsMask;        /* = 0x3F for version "0.42" */
    DWORD   dwFileFlags;            /* e.g. VFF_DEBUG | VFF_PRERELEASE */
    DWORD   dwFileOS;               /* e.g. VOS_DOS_WINDOWS16 */
    DWORD   dwFileType;             /* e.g. VFT_DRIVER */
    DWORD   dwFileSubtype;          /* e.g. VFT2_DRV_KEYBOARD */
    DWORD   dwFileDateMS;           /* e.g. 0 */
    DWORD   dwFileDateLS;           /* e.g. 0 */
} VS_FIXEDFILEINFO;
```

According to [the contribution guidelines](https://github.com/retep998/winapi-rs/blob/0.3/CONTRIBUTING.md#organization-of-code) shouldn't the struct and consts go in a new verrsrc.rs file?

    All definitions go into the source file that directly maps to the header the definition is from. 

Also, the parameter name for `GetFileVersionInfoExA` and `GetFileVersionInfoExW` `lptstrFilename` seems to not match the header (`lpwstrFilename`)
Same thing for `GetFileVersionInfoSizeExA` and `GetFileVersionInfoSizeExW`

Other than that, LGTM

**Comment by roblabla** [comment]
Thanks for the review, will fix.

**Comment by roblabla** [comment]
I took the opportunity to fix some other small mistakes in the winver.rs files (that were backward-compatible). I applied the requested changes, and further changed `*mut c_void` to LPVOID so it matches the header, and reordered some functions so they appear in the same order as the windows header files.

**Comment by nico-abram** [comment]
I think CI failed because of using `use crate::` (I think it might not be supported by the MSRV of `1.6`)

**Comment by roblabla** [comment]
This is ready now.

**Comment by nico-abram** [comment]
LGTM

**Review by nico-abram — APPROVED** [review]
LGTM

**Comment by roblabla** [comment]
https://github.com/retep998/winapi-rs/pull/906 turns out there's an existing PR that's more complete than this one. This should be merged instead.

**Pull request closed without merging**
