### PR TITLE
Add Support for Iphlpapi Libraries, Second Attempt

### PR DESCRIPTION
**Pull request by mattlknight**
This is still a WIP. I picked up where @LuoZijun  left off. I now have all tests passing with no build warnings. I still need to do some code cleanup and confirm that all constants, definitions, and functions have been flushed out.

This is my first ever pull request. My apologies for rookie mistakes, I appreciated any and all commentary/criticism.

Matt

### CODE REVIEW

**Comment by retep998** [comment]
Your git history appears to be slightly bonkers. It seems like you tried to rebase and ended up rebasing a bunch of history that wasn't your PR.

**Comment by mattlknight** [comment]
Oh no!!! I don't even know how that happened. I created a local branch from your repo branch v0.3 and then pulled from https://github.com/LuoZijun/winapi-rs/tree/iphlpapi. I then merged the conflicted files, the same ones that were in PR #572.

Crap. I'll look into this. I'm not really sure how to fix that.

**Comment by mattlknight** [comment]
I think I see what happened. My fork is from your repo, but the branch was somehow created based on https://github.com/LuoZijun/winapi-rs/tree/iphlpapi which is forked from https://github.com/barometz/winapi-rs. The last one is missing all of the commits from your v0.3 branch, so I must have some how merged v0.3 from your repo into that branch, adding all the comits somehow from your repo, into the iphlapi history.

Man I am a ridiculous noob. I'll try to figure out how to fix this.

**Comment by devnought** [comment]
Would a squashed commit on top of 0.3 work @mattlknight @retep998 ?
https://github.com/mattlknight/winapi-rs/pull/2/commits/ce6aeccc76704d632fda07f3ab51df39f6d796bf

**Comment by retep998** [comment]
Squashing the whole thing down is fine.

**Comment by devnought** [comment]
@retep998 Since there hasn't been any traction on this, is it ok if I open a new pull request that has the squashed commit on top of master?

**Comment by mattlknight** [comment]
@devnought @retep998  My apologies, I have been away with work. To be honest, I spent the last few hours trying to get a squash to work. I am having a very hard time getting this to work right. Inexperience and accidents seem to have made this quite difficult for me. Any advice or steps to resolve the squash issue? I don't want to lose all the work that everyone has put into this pull request, but I can't figure out how to remove the invalid commits and squash properly.

**Comment by devnought** [comment]
@mattlknight I went ahead and did the squash on your behalf and submitted a pull request to your fork (https://github.com/mattlknight/winapi-rs/pull/2)

It would still need to be rebased on top of the latest changes in this repo however as I did it a while ago.

**Comment by mattlknight** [comment]
@retep998 @devnought @BlackHoleFox I think I've got it all figured out now with eveyrone's help. Sorry, I've been traveling and moving for a while. I've rebased on top of current 0.3 and all tests are passing. I think this is ready to merge, I think....

**Comment by OMGtechy** [comment]
Any news on this? Otherwise I might be able to carry it on here and there. I need to use GetIpNetTable2, this has GetIpNetTable and would be a stepping stone towards that at least.

**Comment by retep998** [comment]
This PR appears to have been superseded by https://github.com/retep998/winapi-rs/pull/802

**Pull request closed without merging**
