### PR TITLE
Adding LookupAccountNameA and LookupAccountNameW

### PR DESCRIPTION
**Pull request by norbert78**
New pull request based on the (hopefully) correct master branch

### CODE REVIEW

**Comment by retep998** [comment]
CI is failing

**Comment by norbert78** [comment]
OK, just had a look and the issue seems to be about the use of LPCTSTR. 
I would guess that I would have to use LPCSTR or LPCWSTR instead. Is this correct? If this is the case, I would try to re-submit....

**Comment by retep998** [comment]
Yes, you probably want to use `LPCSTR` instead of `LPCTSTR`. Also you need to indent the arguments inside the functions, and you're going over the line length limit.

You don't have to submit a new PR. Instead you can just amend your current commit and then force push it.

**Comment by norbert78** [comment]
Thanks for the advice! I'm still learning :-)
I just issued another commit. I hope that CI passes now.

**Pull request merged**
