### PR TITLE
Porting more APIs to 0.3

### PR DESCRIPTION
**Pull request by Susurrus**
This is blocking on #437, which is why that commit shows up here as well. I've realized merging can be problematic when pulling stuff out of these large older source files, so I've been stacking them up. Maybe I'll submit a bunch as a single PR in the future so the inter-patch dependencies are less of an issue.

I'm filing this now to get a head-start on any compilation builds on CI.

### CODE REVIEW

**Comment by Susurrus** [comment]
Since PRs that pull from the huge advapi32 and kernel32 files from the old 0.2 headers, they trample on each other if left in separate PRs, so I'm combining them into one.

Note that for the `processthreadsapi` commit I used rustfmt to help the process along, but it leaves a trailing comma off the last function argument for function declarations. I'd recommend allowing that and using that as the style instead since rustfmt can automatically format to it and it will drastically speed up porting.

**Comment by Susurrus** [comment]
This work is complete except that the tests expect `sspi` to be listed twice in `build.rs`, which I'm pretty certain it can't, since feature names should be unique. So it won't pass tests until that's fixed.

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Strange, I'll take a look.

**Comment by GuillaumeGomez** [comment]
Ok, I opened a PR to fix this [here](https://github.com/Susurrus/winapi-rs/pull/1).

**Comment by Susurrus** [comment]
@GuillaumeGomez I'm getting other failures related to `src/um/sspi`, notably that it's missing an entry in `build.rs`. I thought this was resolved by #440, but it doesn't look like it.

**Comment by GuillaumeGomez** [comment]
This is supposed to be declared [here](https://github.com/retep998/winapi-rs/pull/440/files#diff-b75d0369b6442f28ac3d71efb82720baR14) and checked [here](https://github.com/retep998/winapi-rs/pull/440/files#diff-b75d0369b6442f28ac3d71efb82720baR43). I'll check this evening.

**Comment by GuillaumeGomez** [comment]
When running the tests over your branch, it works fine for me...

**Comment by Susurrus** [comment]
Interesting. I've pushed again to re-run the tests. We'll see if they pass this time.

**Comment by Susurrus** [comment]
Still not passing on AppVeyor, which is odd. @retep998 Any idea what's going on here?

**Comment by GuillaumeGomez** [comment]
Just to be sure: did you rebase on the target branch?

**Comment by Susurrus** [comment]
@GuillaumeGomez You're right! I thought I had already done this once #440 was merged, but looks like I forgot to. Thanks for catching that.

**Comment by GuillaumeGomez** [comment]
Ok, now it makes sense. :D

**Comment by Susurrus** [comment]
Hmm, still getting the same error. And I've confirmed that your commit 8dea15bf8050d832965490cd87420bb970429137 that should have fixed it is in my branch. It doesn't make sense that you having cloned this branch had it working before either. Something's still not right...

**Comment by GuillaumeGomez** [comment]
Does it work for you when you test locally?

**Comment by Susurrus** [comment]
I don't have a Windows machine to test locally. I borrow a friend's when I can, but I can't currently.

**Comment by Susurrus** [comment]
@GuillaumeGomez I borrowed a Windows computer, and I'm seeing the same things locally. I checked the log and I see your 8dea15bf8050 commit in here. Weird that you can't reproduce on your end.

**Comment by GuillaumeGomez** [comment]
I'll retry. Maybe I failed my rebase.

**Comment by GuillaumeGomez** [comment]
Ok, found the issue. Take a look at #446.

**Comment by Susurrus** [comment]
@GuillaumeGomez #446 worked for me locally, so I rebased this branch on top of that and pushed, so we'll see if it works in CI too.

**Comment by GuillaumeGomez** [comment]
That's another issue now. :D

**Comment by Susurrus** [comment]
@retep998 I think we have a finished PR here, care to take a look-see about merging this?

**Comment by Susurrus** [comment]
@retep998 Can you re-open this? Looks like it was closed automatically by GitHub when it shouldn't have been.

**Comment by retep998** [comment]
I blame @GuillaumeGomez for saying their PR fixed this PR. Unfortunately I cannot reopen.

**Comment by GuillaumeGomez** [comment]
Wait what? PRs can be closed by other PRs? O.o I thought it only did that on issues, sorry...

**Pull request closed without merging**
