### PR TITLE
Add IDWriteFontFace1 interface

### PR DESCRIPTION
**Pull request by vvuk**

### CODE REVIEW

**Comment by retep998** [comment]
Why is this PR against the 0.2 branch?

**Comment by vvuk** [comment]
I'm using 0.2 in dwrote-rs, because I believe 0.2 is already in use in the
bigger picture ecosystem and I didn't want to add 0.3. The PR applies to
the 0.3 branch as well almost identically.

**Comment by Susurrus** [comment]
@vvuk Can you rebase this on the `dev` branch and change this PR to be against that one as well (click the `Edit` button next to the PR title to do that. @retep998 will only accept patches against that branch at this stage.

**Comment by retep998** [comment]
These changes have already landed in `dev` a long time ago.

**Pull request closed without merging**
